# Generated by Django 6.0.1 on 2026-01-13 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('01249143-018a-41d7-8305-7c2451c36f76'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='poll',
            name='voting_mode',
            field=models.CharField(choices=[('open', 'Open voting'), ('restricted', 'Restricted voting')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('total_votes', models.PositiveIntegerField()),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='polls.poll')),
            ],
        ),
    ]
