# Generated by Django 6.0.1 on 2026-01-14 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_public_id_poll_status_poll_voting_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
